version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

